name: Deployment

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Github token
        run: echo ${{ secrets.GITHUB_TOKEN }}
